### ISSUE TITLE
How to leave Cypress open after the tests run?

### ISSUE THREAD

**Issue by dwilches** [jscutlery/devkit#124]
Hello,

Can you add to the documentation how to leave the Cypress window open after a run?

Right now, executing `ng run my-project-here:ct` always closes the window and I need to either go to the videos or look at the text in the terminal.

Thanks.

**Comment by srleecode** [comment]
The ct job calls [this executor](https://github.com/nrwl/nx/blob/master/packages/cypress/src/executors/cypress/schema.json) you can provide any of those options defined in that executor. Setting one of the below ones should allow what you want. You can update the project target or add it when your run it, e.g. ng run my-project-here:ct --watch

```
"watch": {
      "type": "boolean",
      "description": "Recompile and run tests when files change.",
      "default": false
 }
```
```
"exit": {
      "type": "boolean",
      "description": "Whether or not the Cypress Test Runner will stay open after running tests in a spec file",
      "default": true
}
```

**Comment by dwilches** [comment]
Superb, thanks!
--
Daniel Wilches
