### ISSUE TITLE
[swc-plugin-angular] Add vitest support

### ISSUE THREAD

**Issue by yjaaidi** [jscutlery/devkit#305]
Using inline commonjs `require()` was an interesting quick win but switching to using ES imports will allow us to support vitest and any other modern tools.

**Comment by edbzn** [comment]
What about making the module system configurable so we can support both and still have first class Jest support?

**Comment by yjaaidi** [comment]
TL;DR: emitting ES `import`s allows users to choose the module type.

Actually, SWC is already doing that for us using the `module.type` option.
That is why the right way is to emit ES `import`s and let SWC transform that to commonjs `require` or let it as is depending on the `module.type` option.

BTW, when using `@swc/jest`, this option is a no-op because `@swc/jest` will override it depending on Jest's configuration: https://github.com/swc-project/pkgs/blob/f035da2969b45ab9b1810fc2b93be9798ccf8069/packages/jest/index.ts#L55
