### ISSUE TITLE
@jscutlery/operators 2.1.4 doesn't export functions anymore

### ISSUE THREAD

**Issue by Pascalmh** [jscutlery/devkit#315]
This import is not working anymore as of version `2.1.4` (it worked until version 2.1.3)

`import { suspensify } from '@jscutlery/operators';`

instead you have to get it from `import { suspensify } from '@jscutlery/operators/src/lib/suspensify';` which doesn't seem right.

Here are the files in my node_modules:

| 2.1.3 | 2.1.4 |
|--------|--------|
| ![image](https://github.com/jscutlery/devkit/assets/498197/dec17b92-5767-49d0-bb47-5b9b35af0422) | ![image](https://github.com/jscutlery/devkit/assets/498197/bc670de4-28fa-4dab-85cb-5814fcf696a6) |

**Comment by edbzn** [comment]
Hi, yeah we had a release issue where we published source files instead of dist. :sweat_smile: we need to publish a new one, will try to do it soonish. In the meantime, you can use the previous version.

**Comment by yjaaidi** [comment]
Sorry for the inconvenience Pascal!
Fixed in 2.1.5
