### ISSUE TITLE
[playwright-ct-angular] align with the suggested official implementation

### ISSUE THREAD

**Issue by yjaaidi** [jscutlery/devkit#362]
- [x] handle signal inputs
- [x] handle signal outputs
- [x] handle hooks
- [x] handle providers
- [x] handle template mount
- [x] handle template mount with imports

**Comment by haskelcurry** [comment]
Hi, thanks for your great work and apologise for commenting under the closed issue, but it seems that the [model() syntax](https://angular.dev/api/core/model) is not recognized.
