### ISSUE TITLE
[playwright-ct-angular] Support Angular 18

### ISSUE THREAD

**Issue by jfgreffier** [jscutlery/devkit#597]
At the moment, playwright-ct-angular only support Angular 16 and 17. The current version of Angular is 18.x

```json
  "peerDependencies": {
    "@angular/compiler": "^16.0.0 || ^17.0.0",
    "@angular/core": "^16.0.0 || ^17.0.0",
    "@angular/platform-browser": "^16.0.0 || ^17.0.0",
    "@angular/platform-browser-dynamic": "^16.0.0 || ^17.0.0",
    "rxjs": "^7.0.0",
    "zone.js": "*"
  },
  ```
  
  Is there any limitation or issues with Angular 18.x ? Or is it just maintenance (i.e. it was never changed)

**Comment by edbzn** [comment]
We use Angular 18 in the repo so it's a maintenance issue. Thanks for reporting!
