### ISSUE TITLE
[Discussion] - future plans and your opinions on how to best use component testing

### ISSUE THREAD

**Issue by srleecode** [jscutlery/devkit#85]
I am rewriting the [@srleecode/domain generators](https://github.com/srleecode/domain) to move from component testing using storybook to component testing using the cypress test runner through your projects. I really like the work you have done so far on these projects.

I want to start a discussion with you on the future plans you have for these projects and any ideas you have in terms of best practices in regards to component testing and how it should be used when people develop their applications. 

I would also like to know what you think about the draft version of a [component generator](https://github.com/srleecode/domain/tree/master/packages/domain/generators/front-end/angular/component) I have written. This generator can do the following:
 - create a SCAM library for the component. SCAM stands for Single Component Angular Module. SCAMs mean that all feature and UI libraries get their own library. I find this especially useful for component testing as each library can have its own ct target that it can run.
 - add the component test harness file. 
 - add the cy-spec file. To allow things to be setup globally it imports from a global options variable in the [cy-spec](https://github.com/srleecode/domain/blob/master/packages/domain/generators/front-end/angular/component/src/lib/add-component-files/files/__fileName__.cy-spec.ts__tmpl__#L14) or [story file](https://github.com/srleecode/domain/blob/master/packages/domain/generators/front-end/angular/component/src/lib/add-component-files/files/__fileName__.stories.ts__tmpl__#L14). This global options variable could be used for example for including the core things like the Angular material css file. This means that you would only need to setup these core things once.
 - add a story file
 - create the ct target for running the component tests for the component library

**Comment by edbzn** [comment]
Hi @srleecode, 

Super interesting, I have checked your repository and there are really good ideas behind it. We also use SCAMs everywhere but not isolated in a dedicated library by component. I love your idea of having the cypress component spec, the harness file, and the story file along with the component, it's truly something I would like to explore.

I think we could merge our efforts in some way, what do you think?

**Comment by srleecode** [comment]
> I think we could collaborate in some way, what do you think?

That would be great. Let me know what areas you think would good for collaboration and what your plans are for this project. 

[These](https://github.com/srleecode/domain/blob/master/documentation/next/goals.md) are the current goals I have for my project.
